---
# Tasks file for update-os
- name: Update the system using Pacman
  when: ansible_pkg_mgr == "pacman"
  block:
    - name: Update packages using pacman ignoring tree
      ansible.builtin.command: "pacman -Syu --noconfirm --ignore=tree"
      changed_when: false

- name: Upgrade system using apt
  when: ansible_pkg_mgr == "apt"
  block:
    - name: Upgrade OS and update packages except tree
      ansible.builtin.apt:
        upgrade: dist
        update_cache: true
        autoremove: true
        autoclean: true
        state: latest
        exclude: tree

    - name: Install byobu
      ansible.builtin.apt:
        name: byobu
        state: present

    - name: Remove all of the old kernels instead the two latest
      ansible.builtin.command: "purge-old-kernels --keep {{ kernel_versions_to_keep }} -qy"

    - name: Remove byobu
      ansible.builtin.apt:
        name: byobu
        state: absent

- name: Update OS using yum
  when: ansible_pkg_mgr == "yum"
  block:
    - name: Upgrade OS and update packages except tree
      ansible.builtin.yum:
        check_update: true
        name: "*"
        exclude: tree

    - name: Install yum-utils
      ansible.builtin.yum:
        name: yum-utils
        state: present

    - name: Remove all of the old kernels instead the two latest
      ansible.builtin.command: "package-cleanup --old-kernels --count={{ kernel_versions_to_keep }}"

    - name: Remove yum-utils
      ansible.builtin.yum:
        name: yum-utils
        state: absent

- name: Reboot Hosts
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible"
    reboot_timeout: 300
