---

- name: Test Playbook
  hosts: servers
  connection: local
  gather_facts: false
  become: true
  tasks:
    - name: Create an empty file
      ansible.builtin.file:
        mode: "0600"
        path: "/home/poop"
        state: touch
